#! /bin/sh

# consider setting this dynamically
bspc monitor DP-1 -d WWW GFX TRM DOC SYS
bspc monitor DVI-I-1 -d DEV MUS CNF GME VPN

bspc config border_width        3
bspc config window_gap          10
bspc config top_padding         54

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# the only time this is annoying is when trying
# to move tabs between chrome windows.
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true

# solarized-ish colors
bspc config normal_border_color    "#586e75"
bspc config activer_border_color   "#002b36"
bspc config focused_border_color   "#859900"
bspc config presel_feedback_color  "#2aa198"
bspc config urgent_border_color    "#dc322f"

# panel / window rules
bspc rule -a st-sxhkd-help state=floating
